modus: "sommer" # oder sommer
bundesland: "sachsen" # oder sachsen
output_folder: "C:/Users/frede/Desktop/Freddy/2025_Thueringenforst_Schadflaechen/temp_2025"

force:
  ndvi: "Y:/2025_Thueringenforst_Schadflaechen/temp/temp/clipped_NDV.tif"
  ndwi: "Y:/2025_Thueringenforst_Schadflaechen/temp/temp/clipped_NDW.tif"
  nbr: "Y:/2025_Thueringenforst_Schadflaechen/temp/temp/clipped_NBR.tif"
  dswi: "Y:/2025_Thueringenforst_Schadflaechen/temp/temp/clipped_DSW.tif"
  swir1: "Y:/2025_Thueringenforst_Schadflaechen/temp/temp/clipped_SW1.tif"

harmonic_result: "C:/Users/frede/Desktop/Freddy/2025_Thueringenforst_Schadflaechen/temp_2025/harmonic.tif"
analyseflaeche: "C:/Users/frede/Desktop/Freddy/2025_Thueringenforst_Schadflaechen/temp_2025/ana.tif"
result_last_year_summer: "C:/Users/frede/Desktop/Freddy/2025_Thueringenforst_Schadflaechen/results_2024/ergebnis_sommer_2024_rasterized.tif"
result_current_year_spring: "" # Nur benötigt für Modus = "sommer"

maxent: # Parameter training_points & class_attribute nur notwendig bei Berechnung der Klassifikation
  classification: "C:/Users/frede/Desktop/Freddy/2025_Thueringenforst_Schadflaechen/temp_2025/class.tif" # null falls die Klassifikation berechnet werden soll
  training_points: 'Y:/2025_Thueringenforst_Schadflaechen/data_train/visuelle_trainingspunkte.shp'
  class_attribute: 'class_cor' # Attributname welches die Klasse enthält

postprocess:
  ndvi_threshold: 0.1

calc_disturbence: true # Berechnung der Schadflächen

vectorizing: false # false falls nur das Raster ausgegeben werden soll
min_area: 200
